# Numpy exercise

{badge}`python3,badge-success` {badge}`data science,badge-secondary` {badge}`numpy,badge-warning` 

Numpy is 

- Dimensions
- Slicing

{cite}`285005`

In [1]:
import numpy as np

Initializing arrays - pass list

In [2]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
b = np.array([np.arange(4), np.arange(4,8),np.arange(8,12)])
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
c = b[:,np.newaxis]
c

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [5]:
c.shape

(3, 1, 4)

In [6]:
c[2,:,1]

array([9])

In [7]:
c[2]

array([[ 8,  9, 10, 11]])

In [8]:
d = b[np.newaxis,:]
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

(3, 1, 4)

In [9]:
d.shape

(1, 3, 4)

In [10]:
x = np.array([[[ 0,  1,  2,  3],
...                [ 4,  5,  6,  7],
...                [ 8,  9, 10, 11]],
...
...               [[12, 13, 14, 15],
...                [16, 17, 18, 19],
...                [20, 21, 22, 23]]])

In [11]:
x.shape

(2, 3, 4)

In [12]:
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

Normalize x such that each of its rows, within each sheet, will sum to a value of 1. Make use of the sequential function np.sum, which should be called only once, and broadcast-division.



In [13]:
xsum = np.sum(x, axis=(2))
xsum

array([[ 6, 22, 38],
       [54, 70, 86]])

In [14]:
xsum.shape


(2, 3)

In [15]:
x/xsum[...,np.newaxis]

array([[[0.        , 0.16666667, 0.33333333, 0.5       ],
        [0.18181818, 0.22727273, 0.27272727, 0.31818182],
        [0.21052632, 0.23684211, 0.26315789, 0.28947368]],

       [[0.22222222, 0.24074074, 0.25925926, 0.27777778],
        [0.22857143, 0.24285714, 0.25714286, 0.27142857],
        [0.23255814, 0.24418605, 0.25581395, 0.26744186]]])

In [16]:
images = np.random.rand(500, 48, 48, 3)
imgsmall = np.random.rand(3, 4, 4, 3)
imgsmall[0][0]
#stores as a single array

array([[0.60660435, 0.90434785, 0.95061874],
       [0.57178955, 0.03043843, 0.25434074],
       [0.87684583, 0.88876732, 0.02994532],
       [0.35672904, 0.99705469, 0.27664486]])

Using the sequential function np.max and broadcasting, normalize images such that the largest value within each color-channel of each image is 1.

In [17]:
imgsmall[0][0][1]

array([0.57178955, 0.03043843, 0.25434074])

In [18]:
np.max(imgsmall, axis=(1,2))

array([[0.87684583, 0.99705469, 0.97278935],
       [0.96988264, 0.99193012, 0.99452846],
       [0.99884687, 0.90847575, 0.95225873]])

## Bibliography

```{bibliography} ../_bibliography/references.bib
:style: plain
:filter: docname in docnames
```