In [1]:
import numpy as np

In [2]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
b = np.array([np.arange(4), np.arange(4,8),np.arange(8,12)])
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
c = b[:,np.newaxis]
c

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [5]:
c.shape

(3, 1, 4)

In [6]:
c[2,:,1]

array([9])

In [7]:
c[2]

array([[ 8,  9, 10, 11]])

In [8]:
d = b[np.newaxis,:]
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

(3, 1, 4)

In [9]:
d.shape

(1, 3, 4)

In [10]:
x = np.array([[[ 0,  1,  2,  3],
...                [ 4,  5,  6,  7],
...                [ 8,  9, 10, 11]],
...
...               [[12, 13, 14, 15],
...                [16, 17, 18, 19],
...                [20, 21, 22, 23]]])

In [11]:
x.shape

(2, 3, 4)

In [12]:
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [13]:
xsum = np.sum(x, axis=(2))
xsum

array([[ 6, 22, 38],
       [54, 70, 86]])

In [14]:
xsum.shape


(2, 3)

In [15]:
x/xsum[...,np.newaxis]

array([[[0.        , 0.16666667, 0.33333333, 0.5       ],
        [0.18181818, 0.22727273, 0.27272727, 0.31818182],
        [0.21052632, 0.23684211, 0.26315789, 0.28947368]],

       [[0.22222222, 0.24074074, 0.25925926, 0.27777778],
        [0.22857143, 0.24285714, 0.25714286, 0.27142857],
        [0.23255814, 0.24418605, 0.25581395, 0.26744186]]])

In [16]:
images = np.random.rand(500, 48, 48, 3)
imgsmall = np.random.rand(3, 4, 4, 3)
imgsmall[0][0]
#stores as a single array

array([[0.54926616, 0.46880443, 0.59736776],
       [0.24086618, 0.15764314, 0.62312427],
       [0.74155952, 0.14240494, 0.33772703],
       [0.63716097, 0.16649067, 0.27055708]])

In [17]:
imgsmall[0][0][1]

array([0.24086618, 0.15764314, 0.62312427])

In [18]:
np.max(imgsmall, axis=(1,2))

array([[0.91739736, 0.76182266, 0.95340253],
       [0.91420101, 0.98524072, 0.91491591],
       [0.99441115, 0.95667684, 0.97825202]])